# https://hub.docker.com/r/library/node/tags/

image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

#This declares the pipeline stages
stages:
  - test
  - sonar
  - build

cache:
  paths:
    - node_modules/
    
install-dependencies:
  stage: .pre
  script: npm install

run-unit-test:
  stage: test
  script: npm test -u

create-test-coverage-report:
  stage: test
  script: npm run test:coverage
  artifacts:
    paths:
      - coverage
  only:
    - merge_requests
    - master
    - development

include:
  - local: ".gitlab-ci-sonar.yml"

build:
  stage: build
  script:
    - npm run build:prod
  artifacts:
    paths:
      - build
